Repository dohinaf/basic-icecream-website, pull requests merged in 2024-11, with the labels that each got.

#741 Fixed Overlapping Cart, Wishlist, and Search Bars in Navbar
  script.js
Labels: enhancement, level2, gssoc-ext, hacktoberfest-accepted

#734 This PR is related to issue #497.Privacy.html created.
  index.html
  privacy.html
Labels: enhancement, level2, gssoc-ext, hacktoberfest-accepted

#710 Updated README.md
  README.md
Labels: good first issue, level1, gssoc-ext, hacktoberfest-accepted

#809 CHANGED the POP-UP BOX View
  index.html
Labels: enhancement, level1, gssoc-ext, hacktoberfest-accepted

#636 Added cart page
  cart.css
  cart.html
  index.html
  script.js
Labels: level2, gssoc-ext, hacktoberfest-accepted

#552 Using_Trusted_Mail_Services_For_Signup
  signup/signup.html
Labels: level2, gssoc-ext, hacktoberfest-accepted

#769 addition of allergy specification near filter option for more specific choice
  index.html
Labels: enhancement, level1, gssoc-ext, hacktoberfest-accepted

#724 Blog page dark mode update
  blog.html
Labels: enhancement, level1, gssoc-ext, hacktoberfest-accepted

#698 Main
  custom_cursor/images/default-cursor.png
  custom_cursor/images/hover-cursor.png
  custom_cursor/index.html
  custom_cursor/styles.css
Labels: level1, gssoc-ext, hacktoberfest-accepted

#702 Add star rating in review system ISSUE No #463
  index.html
Labels: enhancement, level2, gssoc-ext, hacktoberfest-accepted

#727 added search bar in blog posts
  blog.html
Labels: enhancement, level2, gssoc-ext, hacktoberfest-accepted

#726 Fix Search Bar Text Invisible in Dark Theme
  style.css
Labels: question, issue not present/issue already fixed
