Repository dohinaf/basic-icecream-website, pull requests merged in 2024-10, with the labels that each got.

#189 Issue #114 Added notification tooltip
  index.html
  script.js
  style.css
Labels: gssoc-ext, hacktoberfest-accepted

#165 Update the icecream price
  index.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#173 Update README.md
  README.md
Labels: level1, gssoc-ext, hacktoberfest-accepted

#121 Social icons animation added
  index.html
  style.css
Labels: level1, gssoc-ext, hacktoberfest-accepted

#240 Create Contributors.md
  Contributors.md
Labels: level1, gssoc-ext, hacktoberfest-accepted

#300 Added the pop up discount section
  ICECREAM.jpg
  index.html
Labels: level2, gssoc-ext, hacktoberfest-accepted

#286 Addition of Back2Top Button | Issue #203
  index.html
  script.js
  style.css
Labels: enhancement, level1, gssoc-ext, hacktoberfest-accepted

#193 Added the copyright section
  copyright.html
  index.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#309 ISSUE #235: Increased the padding size of the buttons
  index.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#321 Added a Custom cursor
  chatbot.html
  contact.html
  icecream-details.html
  index.html
Labels: level3, gssoc-ext, hacktoberfest-accepted

#294 Added 'Shop Items' page for displaying details of selected ice cream.
  berry_pops.html
  cherry_pops.html
  choco_hazel.html
  drip_vanilla.html
  images/08-1333x2000.jpg
  images/download (1).jpeg
  images/download (2).jpeg
  images/download (3).jpeg
  images/download (4).jpeg
  images/download (5).jpeg
  images/download (6).jpeg
  images/download (7).jpeg
  images/download (8).jpeg
  images/download (9).jpeg
  images/download.jpeg
  images/images (1).jpeg
  images/images.jpeg
  index.html
  nut_butter.html
  orange_pops.html
  orange_pops1.html
  rain_classic.html
  very_peachy.html
  very_peachy2.html
  very_straw.html
Labels: level3, gssoc-ext, hacktoberfest-accepted

#329 feat: Improved Login and Sign-up buttons
  index.html
  style.css
Labels: level1, gssoc-ext, hacktoberfest-accepted

#332 sign-up and sign-in form with new design
  index.html
  style.css
Labels: level1, gssoc-ext, hacktoberfest-accepted

#333 Added animated review and animated contact page.
  contact.html
  index.html
Labels: level3, gssoc-ext, hacktoberfest-accepted

#340 ADDED THE COOL BUTTON
  index.html
Labels: level2, gssoc-ext, hacktoberfest-accepted

#348 Styled the vertical scrollbar
  style.css
Labels: enhancement, gssoc-ext, hacktoberfest-accepted

#358 Add 'Remove Filter' functionality and enhance ice cream filtering.
  index.html
  script.js
Labels: enhancement, level1, gssoc-ext, hacktoberfest-accepted

#372 Updated review layout section and fixed submit button overlap isuue
  index.html
  style.css
Labels: level1, gssoc-ext, hacktoberfest-accepted

#410 Icecream website Login page Re-Design.
  index.html
  script.js
  style.css
Labels: level2, gssoc-ext, hacktoberfest-accepted

#429 {DOC} Ennhanced README.md
  README.md
  blogs.png
  gssoc24.png
  hacktoberfest.png
  home.png
  menu.png
Labels: level1, gssoc-ext, hacktoberfest-accepted

#481 Position of Elements is Adjusted Successfully
  style.css
Labels: level1, gssoc-ext, hacktoberfest-accepted

#378 Enhanced Ice-Cream Cards Animations & Button Functionality!
  style.css
Labels: level1, gssoc-ext, hacktoberfest-accepted

#491 Menu filter section update in dark mode
  index.html
  style.css
Labels: enhancement, level1, gssoc-ext, hacktoberfest-accepted

#433 Add different hover effects in the given Nav bar section so that it looks more attractive and change the color whenever the cursor moves there.
  contact.html
  icecream-details.html
  style.css
  styles.css
Labels: level1, gssoc-ext, hacktoberfest-accepted

#455 modified checkout page
  index.html
  script.js
Labels: level1, gssoc-ext, hacktoberfest-accepted

#521 Fixed the Clear wishlist button
  style.css
Labels: level1, gssoc-ext, hacktoberfest-accepted

#224 Create customer review page (new design)
  About us page (new design)
  Screenshot 2024-10-04 120235.png
  Screenshot 2024-10-04 161842.png
  Screenshot 2024-10-04 170108.png
  Screenshot 2024-10-04 170136.png
  customer review page (new design)
Labels: level2, gssoc-ext, hacktoberfest-accepted

#233 Improved footer #167
  README.md
  blogs.png
  contact.html
  contributing.md
  gssoc24.png
  hacktoberfest.png
  home.png
  icecream-details.html
  index.html
  login/login.css
  login/login.html
  login/login.js
  menu.png
  preloader.js
  preloaderStyle.css
  script.js
  signup/signup.css
  signup/signup.html
  signup/signup.js
  style.css
  styles.css
Labels: level1, gssoc-ext, hacktoberfest-accepted

#278 Add mini cahtbot to the website
  chatbot.html
  index.html
Labels: level3, gssoc-ext, hacktoberfest-accepted

#560 Added brand color hover effect for media icons.
  index.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#542 footer social icon and customer button hover text visible
  index.html
  style.css
Labels: level1, gssoc-ext, hacktoberfest-accepted

#573 Fixed Contact Page
  About us page (new design)
  HomepageIMG2.png
  Screenshot 2024-10-04 120235.png
  Screenshot 2024-10-04 161842.png
  Screenshot 2024-10-04 170108.png
  Screenshot 2024-10-04 170136.png
  berry_pops.html
  blog.html
  chatbot.html
  cherry_pops.html
  choco_hazel.html
  contact.html
  copyright.html
  customer review page (new design)
  drip_vanilla.html
  icecream-details.html
  index.html
  login/login.html
  nut_butter.html
  orange_pops.html
  orange_pops1.html
  rain_classic.html
  signup/signup.html
  style.css
  very_peachy.html
  very_peachy2.html
  very_straw.html
Labels: level2, gssoc-ext, hacktoberfest-accepted

#627 ADDED OFFERS PAGE
  OFFER1.png
  OFFER2.png
  OFFER3.png
  blog.html
  contact.html
  index.html
  offers.html
Labels: level2, gssoc-ext, hacktoberfest-accepted

#443 Implement Separate Profile Pages with Enhanced User Functionality
  bg2.png
  facebook.png
  google.png
  index.html
  instagram.png
  login/login.html
  login/login.js
  profile.html
  profile.js
  profilepic.png
  signup/signup.html
  signup/signup.js
Labels: level3, gssoc-ext, hacktoberfest-accepted
